# permissions for end users to edit packers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packer-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - packers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - packers/status
  verbs:
  - get
