# permissions for end users to view packers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packer-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - packers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - packers/status
  verbs:
  - get
